# Generated by Django 4.0.2 on 2022-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
